### ISSUE TITLE
Need share button and accurate footer (for 2012 Cosmic/Epic Panda), accurate footer (early 2016-2020/unofficial 2024 Hitchhiker) and prototypes of early 2009 (Stargazer) and early 2012 (Cosmic Panda)

### ISSUE THREAD

**Issue by gigigigi53** [iamnotrandom565/v3-userstyles-scripts#10]
Like these:
![Screenshot 2024-12-15 191654](https://github.com/user-attachments/assets/f1a7efee-edc5-4c6c-b69f-e50858a7df97)
![Screenshot 2024-12-15 194732](https://github.com/user-attachments/assets/3a470577-d662-47fb-a070-c0bc09f93193)

(share button/G+ and footer)

![Screenshot 2024-12-15 190458](https://github.com/user-attachments/assets/1ac1d3c4-108b-4b8a-861f-f8d4f1ea8ad2)
(footer, includes History, Help and +YouTube)

![Screenshot 2024-12-15 191534](https://github.com/user-attachments/assets/190b5b29-23f0-457a-ab1c-409349e9cd78)
![Screenshot 2024-12-15 191552](https://github.com/user-attachments/assets/f2b237df-934f-4d1b-91b6-16cd5b47294a)
(the early 2009/2012 prototypes)

Thank you!

**Comment by gigigigi53** [comment]
Also the Create Account | Sign In (2010-mid 2012) and Sign In (late 2012), along with the sign in messages:

![Screenshot 2024-12-15 192744](https://github.com/user-attachments/assets/74ef10aa-7db0-44a4-850a-a3f4d8f2cd16)
(2010-mid 2012)

![Screenshot 2024-12-15 192748](https://github.com/user-attachments/assets/b1fc8111-0f65-45f1-9d9d-0dcfe9385edd)

![Screenshot 2024-12-15 192751](https://github.com/user-attachments/assets/e98dc9c4-5b84-4692-9010-0392d0ab7323)
(both late 2012)

![Screenshot 2024-12-15 192733](https://github.com/user-attachments/assets/6d57b8c1-467f-49f6-b56f-62b2db3219a4)
(early-mid 2012)

![Screenshot 2024-12-15 192739](https://github.com/user-attachments/assets/ba5e560a-7f0c-497c-99ea-476b3a1f5ce2)
(late 2012)

**Comment by gigigigi53** [comment]
The names of the userstyles:
1. 2012 Share button and accurate footer
2. 2013+ Accurate footer
3. 2010-2012 Sign In Button and bar
4. Prototype Early 2009 and Prototype Early 2012 (2 separate userstyles)

How do they work:
1. Adds a Google+ share button, makes the footer accurate and opens Google Support by clicking Help (and adds copyright date to the bottom on older versions of StarTube)
2. Makes the footer accurate and opens Google Support by clicking Help from the footer (and adds copyright date to the bottom on older versions of StarTube)
3.  Makes the sign in buttons and bar look a lot like its accurate counterparts
4. It will have the prototype look and feel by changing some stuff to look like them

Toggles/switches:
1. None
2. Which year do you want to look like? (2013, 2014, 2015, 2016-2020/2024, 2016-2020/2024 selected by default), +YouTube Button (disabled by default)
3. Which month? (Early-Mid, Late, Late selected by default), Former or latter late 2012 blank profile? (Former, latter, former selected by default)
4. None

**Comment by iamnotrandom565** [comment]
I'm pretty sure I'm not a genie, so I can't grant every wish

**Comment by iamnotrandom565** [comment]
also you asked the same thing to lightbeam24

**Comment by gigigigi53** [comment]
> also you asked the same thing to lightbeam24

i apologize i just want to make it accurate.. sorry

**Comment by gigigigi53** [comment]
> I'm pretty sure I'm not a genie, so I can't grant every wish

but there might be some of them...
