### ISSUE TITLE
Need 2006-2008 player (for the StarTube 2008 layout)

### ISSUE THREAD

**Issue by gigigigi53** [iamnotrandom565/v3-userstyles-scripts#8]
Something like this:
![Screenshot 2024-11-23 152546](https://github.com/user-attachments/assets/8b8e3618-b301-47a9-8b3a-10be5c919b97)

This will have all the late 2006-early 2008 counterparts, and for the late 2006-early 2007 look, it will have the **Loading...** text instead of the loading circle (mid 2007-2017).
:
![Screenshot 2024-11-23 152834](https://github.com/user-attachments/assets/09c00377-41c3-4d88-b021-95ce11bf30b5)

The userstyle settings will be:
- Use **Loading...** text instead of loading circle (off by default)
- Disable captions and settings buttons (on by default)
- Enable previous button (on by default)

Alright, thank you.

**Comment by iamnotrandom565** [comment]
When I find images / sprites of the buttons, I'll start working on it

**Comment by mrkrabs206** [comment]
> When I find images / sprites of the buttons, I'll start working on it

You could extract from the late 2006 and mid 2007 players

**Comment by gigigigi53** [comment]
https://www.mediafire.com/file/cxlzm3hrvqw61b2/2007e.swf/file (use ffdec/JPEXS to extract sprites, images and buttons)

**Comment by iamnotrandom565** [comment]
somebody already made an html5 version here

i'm going to make it now.
